### ISSUE TITLE
Voting Buttons are b0rked

### ISSUE THREAD

**Issue by alastairs** [dddeastanglia/DDDEastAnglia#142]
Clicking the Vote button against any of the sessions on the staging site (or a development site) seems to have no effect at all. Anyone else seeing this?

**Comment by adrianbanks** [comment]
I see it on my local site - an error saving the vote object back to the database. I currently cannot see why, as it throws an exception inside EF that I cannot inspect while debugging. I'll have to add some logging code to see what the issue is.

I get the same behaviour on the staging site as well, although I didn't earlier on this evening.
