### ISSUE TITLE
Store extra information about the conference

### ISSUE THREAD

**Issue by adrianbanks** [dddeastanglia/DDDEastAnglia#289]
A lot of the pages in the voting area use the number of total sessions when displaying the graphs. It would be good to get this from the database, from information associated with the conference.

**Comment by alastairs** [comment]
The purpose of the "top 15 sessions" screens in the admin voting area is to give us an idea of what our agenda will look like. Last year we only had 3 tracks x 5 slots = 15 sessions, but this year we will have 4 or 5 tracks x 5 slots = 20 or 25 sessions. This setting should be surfaced through the admin UI rather than through a config change or const in the code.
