### ISSUE TITLE
Be able to dismiss the "shouty" box

### ISSUE THREAD

**Issue by adrianbanks** [dddeastanglia/DDDEastAnglia#41]
Alastair is keen to be able to dismiss the shouty box that appears on some pages so that it doesn't get shown again.

Need to consider whether it reappears when the thing it is shouting about changes (e.g. session submission -> voting).

**Comment by alastairs** [comment]
I just tried playing around with this with the Bootstrap alert functionality. It's not possible to permanently dismiss the banner because alerts are intended to be transitory: they appear once and you can dismiss it if you wish. 

To permanently dismiss the banner, we will need to set a cookie, that can be invalidated when the announcement is changed.

**Comment by adrianbanks** [comment]
Fixed by #47.
